name: 'Deploy to AWS S3'
description: 'Deploy a static website via AWS S3'
inputs:
  bucket:
    description: 'The S3 bucket name.'
    required: true
  bucket-region:
    description: "Region of the bucket."
    required: false
    default: 'ap-south-1'
  dist-folder:
    description: 'The folder containing the deployable files.'
    required: true
outputs:
  website-url:
    description: URL of the deployed website
runs:
  using: 'node24'
  # pre: 'pre.js'
  main: 'main.js'
  # post: 'post.js'