name: First Workflow
on: workflow_dispatch
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello world!"
      - name: os version
        run: uname -a
      - name: Print Goodbye
        run: echo "Done - Bye!"
