name: Build reusable workflow
on:
    workflow_call:
        outputs:
            script-file: 
                description: JS files created by build job
                value: ${{ jobs.build-react-app.outputs.script-file}}
jobs:
    build-react-app:
        runs-on: self-hosted
        outputs:
            script-file: ${{ steps.publish.outputs.script-file }}
        steps:
        -   name: Get code
            uses: actions/checkout@v5
        -   name: setup node environment
            uses: ./.github/actions/node-env-setup
            
        -   name: Build project
            run: |
                pwd
                ls -alsh
                npm run build
        -   name: Publish JS file name in job output
            id: publish
            run: find dist/assets/*.js -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';'
            
        -   name: Upload artifact
            uses: actions/upload-artifact@v4
            with:
                name: dist-files
                path: |
                    dist
                    package.json
            