name: Test and deploy react app
on: 
  pull_request:
    types:
      - opened
      - reopened
      - edited
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  lint-react-app:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v5
      - name: Install NodeJS
        uses: actions/setup-node@v5
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Lint react app
        run: npm run lint
      
  test-react-app:
    needs: lint-react-app
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v5
      - name: Install NodeJS
        uses: actions/setup-node@v5
        with: 
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
        
  build-react-app:
    needs: test-react-app
    runs-on: ubuntu-latest
    outputs:
      script-file: hello
    steps:
      - name: Get code
        uses: actions/checkout@v5
      - name: Install NodeJS
        uses: actions/setup-node@v5
        with:
          node-version: 18
      - name: Install dependenceis
        run: |
          pwd
          npm ci
      - name: Build project
        run: |
          pwd
          npm run build
      - name: Publish JS file name in job output
        id: publish
        run: find dist/assets/*.js -type f -execdir echo 'script=file={}' >> $GITHUB_OUTPUT ';'
        
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: |
            dist
            package.json
            
  deploy-react-app:
    needs: build-react-app
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v5
        with:
          name: dist-files
      - name: Output contents
        run: |
          pwd
          ls -alsh
          du -sh *
      - name: Deploy build
        run: echo "Deploying ..."
        
        
