name: Deploy Reusable workflow
on:
  workflow_call:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v5
        with:
          name: dist-files
      - name: Deploy
        run: echo "Deploying ..."