name: Test and deploy react app
on: 
  pull_request:
    types:
      - opened
      - reopened
      - edited
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  lint-react-app:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v5
      - name: Install NodeJS
        uses: actions/setup-node@v5
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Lint react app
        run: npm run lint
      
  test-react-app:
    needs: lint-react-app
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v5
      - name: Install NodeJS
        uses: actions/setup-node@v5
        with: 
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
  deploy-react-app:
    needs: test-react-app
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v5
      - name: Install NodeJS
        uses: actions/setup-node@v5
        with:
          node-version: 18
      - name: Install dependenceis
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: |
            dist
            package.json
      - name: Deploy
        run: echo "Deploying ..."
        
        
